spring:
  application:
    name: BasicAuth
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${your.client.id}
            client-secret: ${your.client.secret}
            scope:
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          google:
            issuer-uri: https://accounts.google.com


#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  datasource:
    url: jdbc:postgresql://localhost:5432/ems
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver


  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail}
    password: ${mail.password}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect


mail: ${mail}
server:
  port: 8081

admin:
  name: ${admin.name}
  surname: ${admin.surname}
  password: ${admin.password}
  email: ${admin.email}


jwt:
  access-token-expire-time: ${ONE_DAY}
  refresh-token-expire-time: ${ONE_DAY}
  secretKey: ${JWT_SECRET_KEY}



